apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_service
  namespace: your-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user_service
  template:
    metadata:
      labels:
        app: user_service
    spec:
      containers:
      - env: []
        image: your-registry/user_service:latest
        name: user_service
        ports:
        - containerPort: 5000
